### PR TITLE
A bit of clean up

### PR DESCRIPTION
**Pull request by MrGcGamer**
Merged the hooks
fixed some typos

So I saw your release post on Reddit and as well as it being open source so I looked at the code... I found a bit of unnessesarry stuff as well as quite a few things which aren't doing anything.

### CODE REVIEW

**Comment by acrxhd** [comment]
Yeah I was planning on cleaning it up. I'll test it and include it in v1.1.1, as I just finished the beta for v.1.1.0 and have submitted it to big boss for approval

**Comment by ja1dan** [comment]
> Merged the hooks
> fixed some typos
> 
> So I saw your release post on Reddit and as well as it being open source so I looked at the code... I found a lot of useless stuff as well as quite a few things which aren't doing anything.
> I hurt a bit to look at so I decided to make a pull request real quick

hey, for future reference, don't be so mean about it. try to say it nicer; the way you said it might hurt somebody's feelings.

**Comment by tomdvies** [comment]
dont be an ass bruh

**Comment by MrGcGamer** [comment]
I am sorry if I hurt anybodies feelings... that wasn't my intention...

**Comment by acrxhd** [comment]
> I am sorry if I hurt anybodies feelings... that wasn't my intention...

It's fine. You didn't hurt my feelings. I'm still learning how to do all of this

**Pull request closed without merging**
